taskkill /IM explorer.exe /F
taskkill /IM explorer.exe /F
taskkill /IM explorer.exe /F
taskkill /IM explorer.exe /F
taskkill /IM explorer.exe /F
Taskkill /f /im explorer.exe
Taskkill /f /im explorer.exe
taskkill /IM chrome.exe /F
taskkill /IM notepad.exe /F
taskkill /IM calc.exe /F